-- AlterTable
ALTER TABLE "TCSCON" ADD COLUMN     "CODPROJ" BIGINT,
ADD COLUMN     "DTREFPROXFAT" DATE,
ADD COLUMN     "DTTERMINO" DATE,
ADD COLUMN     "PARCELAQTD" INTEGER,
ADD COLUMN     "TIPO" CHAR(1) NOT NULL DEFAULT 'M',
ADD COLUMN     "VLRHORA" DECIMAL(15,2);

-- AlterTable
ALTER TABLE "TCSPRJ" DROP COLUMN "DESCRPROJ",
ADD COLUMN     "ABREVIATURA" TEXT NOT NULL,
ADD COLUMN     "ANALITICO" CHAR(1) NOT NULL DEFAULT 'S',
ADD COLUMN     "CODPROJPAI" BIGINT,
ADD COLUMN     "CODUSURESP" BIGINT,
ADD COLUMN     "CONCLUIDO" CHAR(1) NOT NULL DEFAULT 'N',
ADD COLUMN     "DTINICIO" DATE,
ADD COLUMN     "DTTERMINO" DATE,
ADD COLUMN     "GRAU" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "IDENTIFICACAO" TEXT NOT NULL,
ADD COLUMN     "VLRORCADO" DECIMAL(15,2);

-- AddForeignKey
ALTER TABLE "TCSPRJ" ADD CONSTRAINT "TCSPRJ_CODPROJPAI_fkey" FOREIGN KEY ("CODPROJPAI") REFERENCES "TCSPRJ"("CODPROJ") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TCSCON" ADD CONSTRAINT "TCSCON_CODPROJ_fkey" FOREIGN KEY ("CODPROJ") REFERENCES "TCSPRJ"("CODPROJ") ON DELETE SET NULL ON UPDATE CASCADE;

