-- AlterTable
ALTER TABLE "TSXTEN" ADD COLUMN     "PROVEDORIA" TEXT NOT NULL DEFAULT 'nuvem';

-- CreateTable
CREATE TABLE "TREIAANALISE" (
    "CODIAANALISE" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCDT" BIGINT NOT NULL,
    "CONTEUDOJSON" JSONB NOT NULL,
    "HASHENTRADA" TEXT NOT NULL,
    "PROVEDOR" TEXT,
    "MODELOUSADO" TEXT,
    "VERSAOPROMPT" TEXT,
    "DURACAOMS" INTEGER,
    "STATUS" TEXT NOT NULL DEFAULT 'OK',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,

    CONSTRAINT "TREIAANALISE_pkey" PRIMARY KEY ("CODIAANALISE")
);

-- CreateIndex
CREATE INDEX "TREIAANALISE_CODTEN_CODCDT_idx" ON "TREIAANALISE"("CODTEN", "CODCDT");

-- AddForeignKey
ALTER TABLE "TREIAANALISE" ADD CONSTRAINT "TREIAANALISE_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREIAANALISE" ADD CONSTRAINT "TREIAANALISE_CODCDT_fkey" FOREIGN KEY ("CODCDT") REFERENCES "TRECDT"("CODCDT") ON DELETE RESTRICT ON UPDATE CASCADE;


-- SelX: RLS (ADR-0002) — TREIAANALISE guarda análise de candidato por tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TREIAANALISE'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
