-- CreateTable
CREATE TABLE "TGPPDI" (
    "CODPDI" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODFUN" BIGINT NOT NULL,
    "TITULO" TEXT NOT NULL,
    "OBJETIVO" TEXT,
    "CODUSURESP" BIGINT,
    "DTINICIO" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTREVISAO" DATE,
    "STATUS" TEXT NOT NULL DEFAULT 'ATIVO',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,

    CONSTRAINT "TGPPDI_pkey" PRIMARY KEY ("CODPDI")
);

-- CreateTable
CREATE TABLE "TGPACAO" (
    "CODACAO" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODPDI" BIGINT NOT NULL,
    "DESCRICAO" TEXT NOT NULL,
    "TIPO" TEXT NOT NULL DEFAULT 'TREINAMENTO',
    "COMPETENCIA" TEXT,
    "PRAZO" DATE,
    "STATUS" TEXT NOT NULL DEFAULT 'PENDENTE',
    "PROGRESSO" INTEGER NOT NULL DEFAULT 0,
    "DHCONCLUSAO" TIMESTAMP(3),
    "ORDEM" INTEGER NOT NULL DEFAULT 0,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TGPACAO_pkey" PRIMARY KEY ("CODACAO")
);

-- CreateIndex
CREATE INDEX "TGPPDI_CODTEN_CODFUN_idx" ON "TGPPDI"("CODTEN", "CODFUN");

-- CreateIndex
CREATE INDEX "TGPACAO_CODTEN_CODPDI_idx" ON "TGPACAO"("CODTEN", "CODPDI");

-- AddForeignKey
ALTER TABLE "TGPPDI" ADD CONSTRAINT "TGPPDI_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPPDI" ADD CONSTRAINT "TGPPDI_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPPDI" ADD CONSTRAINT "TGPPDI_CODUSURESP_fkey" FOREIGN KEY ("CODUSURESP") REFERENCES "TSIUSU"("CODUSU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPACAO" ADD CONSTRAINT "TGPACAO_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPACAO" ADD CONSTRAINT "TGPACAO_CODPDI_fkey" FOREIGN KEY ("CODPDI") REFERENCES "TGPPDI"("CODPDI") ON DELETE RESTRICT ON UPDATE CASCADE;


-- SelX: RLS (ADR-0002) — PDI e ações são dados do funcionário, por tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TGPPDI','TGPACAO'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
