-- CreateTable
CREATE TABLE "TSXKIT" (
    "CODKIT" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "NOMEKIT" TEXT NOT NULL,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TSXKIT_pkey" PRIMARY KEY ("CODKIT")
);

-- CreateTable
CREATE TABLE "TSXKITDOC" (
    "CODKITDOC" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODKIT" BIGINT NOT NULL,
    "CODDOC" BIGINT NOT NULL,
    "ORDEM" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "TSXKITDOC_pkey" PRIMARY KEY ("CODKITDOC")
);

-- CreateTable
CREATE TABLE "TREADMPROC" (
    "CODADMPROC" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCDT" BIGINT NOT NULL,
    "STATUS" TEXT NOT NULL DEFAULT 'AGUARDANDO_CANDIDATO',
    "TOKENPUB" TEXT NOT NULL,
    "DADOSCOMPLEMENTARESJSON" JSONB,
    "OBSAJUSTE" TEXT,
    "DHINICIO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHENVIOCANDIDATO" TIMESTAMP(3),
    "DHAPROVACAO" TIMESTAMP(3),
    "CODUSUAPROV" BIGINT,
    "CODUSUINC" BIGINT,

    CONSTRAINT "TREADMPROC_pkey" PRIMARY KEY ("CODADMPROC")
);

-- CreateTable
CREATE TABLE "TREADMANEXO" (
    "CODADMANEXO" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODADMPROC" BIGINT NOT NULL,
    "CATEGORIA" TEXT NOT NULL,
    "ARQUIVO" TEXT NOT NULL,
    "NOMEORIGINAL" TEXT NOT NULL,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TREADMANEXO_pkey" PRIMARY KEY ("CODADMANEXO")
);

-- CreateIndex
CREATE UNIQUE INDEX "TSXKITDOC_CODKIT_CODDOC_key" ON "TSXKITDOC"("CODKIT", "CODDOC");

-- CreateIndex
CREATE UNIQUE INDEX "TREADMPROC_CODCDT_key" ON "TREADMPROC"("CODCDT");

-- CreateIndex
CREATE UNIQUE INDEX "TREADMPROC_TOKENPUB_key" ON "TREADMPROC"("TOKENPUB");

-- CreateIndex
CREATE INDEX "TREADMANEXO_CODTEN_CODADMPROC_idx" ON "TREADMANEXO"("CODTEN", "CODADMPROC");

-- AddForeignKey
ALTER TABLE "TSXKIT" ADD CONSTRAINT "TSXKIT_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXKITDOC" ADD CONSTRAINT "TSXKITDOC_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXKITDOC" ADD CONSTRAINT "TSXKITDOC_CODKIT_fkey" FOREIGN KEY ("CODKIT") REFERENCES "TSXKIT"("CODKIT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXKITDOC" ADD CONSTRAINT "TSXKITDOC_CODDOC_fkey" FOREIGN KEY ("CODDOC") REFERENCES "TSXDOC"("CODDOC") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREADMPROC" ADD CONSTRAINT "TREADMPROC_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREADMPROC" ADD CONSTRAINT "TREADMPROC_CODCDT_fkey" FOREIGN KEY ("CODCDT") REFERENCES "TRECDT"("CODCDT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREADMANEXO" ADD CONSTRAINT "TREADMANEXO_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREADMANEXO" ADD CONSTRAINT "TREADMANEXO_CODADMPROC_fkey" FOREIGN KEY ("CODADMPROC") REFERENCES "TREADMPROC"("CODADMPROC") ON DELETE RESTRICT ON UPDATE CASCADE;


-- SelX: RLS (ADR-0002)
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TSXKIT','TSXKITDOC','TREADMPROC','TREADMANEXO'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
