-- CreateTable
CREATE TABLE "TRETAG" (
    "CODTAG" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "NOME" TEXT NOT NULL,
    "COR" TEXT NOT NULL DEFAULT '#8A5B3F',
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,

    CONSTRAINT "TRETAG_pkey" PRIMARY KEY ("CODTAG")
);

-- CreateTable
CREATE TABLE "TRECANDTAG" (
    "CODCANDTAG" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCAND" BIGINT NOT NULL,
    "CODTAG" BIGINT NOT NULL,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,

    CONSTRAINT "TRECANDTAG_pkey" PRIMARY KEY ("CODCANDTAG")
);

-- CreateTable
CREATE TABLE "TRECDTFAV" (
    "CODFAV" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCDT" BIGINT NOT NULL,
    "CODUSU" BIGINT NOT NULL,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TRECDTFAV_pkey" PRIMARY KEY ("CODFAV")
);

-- CreateTable
CREATE TABLE "TREFILTRO" (
    "CODFILTRO" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODUSU" BIGINT NOT NULL,
    "NOME" TEXT NOT NULL,
    "FILTROSJSON" JSONB NOT NULL,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TREFILTRO_pkey" PRIMARY KEY ("CODFILTRO")
);

-- CreateIndex
CREATE UNIQUE INDEX "TRETAG_CODTEN_NOME_key" ON "TRETAG"("CODTEN", "NOME");

-- CreateIndex
CREATE INDEX "TRECANDTAG_CODTEN_CODTAG_idx" ON "TRECANDTAG"("CODTEN", "CODTAG");

-- CreateIndex
CREATE UNIQUE INDEX "TRECANDTAG_CODCAND_CODTAG_key" ON "TRECANDTAG"("CODCAND", "CODTAG");

-- CreateIndex
CREATE INDEX "TRECDTFAV_CODTEN_CODUSU_idx" ON "TRECDTFAV"("CODTEN", "CODUSU");

-- CreateIndex
CREATE UNIQUE INDEX "TRECDTFAV_CODCDT_CODUSU_key" ON "TRECDTFAV"("CODCDT", "CODUSU");

-- CreateIndex
CREATE UNIQUE INDEX "TREFILTRO_CODTEN_CODUSU_NOME_key" ON "TREFILTRO"("CODTEN", "CODUSU", "NOME");

-- AddForeignKey
ALTER TABLE "TRETAG" ADD CONSTRAINT "TRETAG_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECANDTAG" ADD CONSTRAINT "TRECANDTAG_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECANDTAG" ADD CONSTRAINT "TRECANDTAG_CODCAND_fkey" FOREIGN KEY ("CODCAND") REFERENCES "TRECAND"("CODCAND") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECANDTAG" ADD CONSTRAINT "TRECANDTAG_CODTAG_fkey" FOREIGN KEY ("CODTAG") REFERENCES "TRETAG"("CODTAG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECDTFAV" ADD CONSTRAINT "TRECDTFAV_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECDTFAV" ADD CONSTRAINT "TRECDTFAV_CODCDT_fkey" FOREIGN KEY ("CODCDT") REFERENCES "TRECDT"("CODCDT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECDTFAV" ADD CONSTRAINT "TRECDTFAV_CODUSU_fkey" FOREIGN KEY ("CODUSU") REFERENCES "TSIUSU"("CODUSU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREFILTRO" ADD CONSTRAINT "TREFILTRO_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREFILTRO" ADD CONSTRAINT "TREFILTRO_CODUSU_fkey" FOREIGN KEY ("CODUSU") REFERENCES "TSIUSU"("CODUSU") ON DELETE RESTRICT ON UPDATE CASCADE;


-- SelX: RLS (ADR-0002) — as quatro são por tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TRETAG','TRECANDTAG','TRECDTFAV','TREFILTRO'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
