-- CreateTable
CREATE TABLE "TREPROP" (
    "CODPROP" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCDT" BIGINT NOT NULL,
    "VLRSALARIO" DECIMAL(15,2) NOT NULL,
    "DTINICIO" DATE,
    "TIPOCONTRATO" TEXT,
    "BENEFICIOS" TEXT,
    "OBSERVACOES" TEXT,
    "STATUS" TEXT NOT NULL DEFAULT 'RASCUNHO',
    "TOKENPUB" TEXT,
    "DHENVIO" TIMESTAMP(3),
    "DHRESPOSTA" TIMESTAMP(3),
    "MOTIVORECUSA" TEXT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,

    CONSTRAINT "TREPROP_pkey" PRIMARY KEY ("CODPROP")
);

-- CreateIndex
CREATE UNIQUE INDEX "TREPROP_TOKENPUB_key" ON "TREPROP"("TOKENPUB");

-- CreateIndex
CREATE INDEX "TREPROP_CODTEN_CODCDT_idx" ON "TREPROP"("CODTEN", "CODCDT");

-- AddForeignKey
ALTER TABLE "TREPROP" ADD CONSTRAINT "TREPROP_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREPROP" ADD CONSTRAINT "TREPROP_CODCDT_fkey" FOREIGN KEY ("CODCDT") REFERENCES "TRECDT"("CODCDT") ON DELETE RESTRICT ON UPDATE CASCADE;


-- SelX: RLS (ADR-0002) — proposta é dado por tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TREPROP'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
