-- AlterTable
ALTER TABLE "TRECAND" ADD COLUMN     "PERFILCULTURALJSON" JSONB;

-- AlterTable
ALTER TABLE "TRECDT" ADD COLUMN     "AUTOAVALIACAOJSON" JSONB;

-- AlterTable
ALTER TABLE "TREVAG" ADD COLUMN     "PERFILCULTURALIDEALJSON" JSONB;

-- AlterTable
ALTER TABLE "TREVAGREQ" ADD COLUMN     "EVIDENCIAEXIGIDA" CHAR(1) NOT NULL DEFAULT 'N',
ADD COLUMN     "NIVELESPERADO" INTEGER,
ADD COLUMN     "PESO" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "TEMPOESPMESES" INTEGER;
