-- CreateTable
CREATE TABLE "TREENTREVHOR" (
    "CODHOR" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODVAG" BIGINT NOT NULL,
    "DHINICIO" TIMESTAMP(3) NOT NULL,
    "DURACAOMIN" INTEGER NOT NULL DEFAULT 45,
    "TIPO" TEXT NOT NULL DEFAULT 'VIDEO',
    "LOCAL" TEXT,
    "LINKREUNIAO" TEXT,
    "CODUSUENTREV" BIGINT,
    "STATUS" TEXT NOT NULL DEFAULT 'LIVRE',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,

    CONSTRAINT "TREENTREVHOR_pkey" PRIMARY KEY ("CODHOR")
);

-- CreateTable
CREATE TABLE "TREENTREV" (
    "CODENTREV" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCDT" BIGINT NOT NULL,
    "CODHOR" BIGINT,
    "DHINICIO" TIMESTAMP(3) NOT NULL,
    "DURACAOMIN" INTEGER NOT NULL DEFAULT 45,
    "TIPO" TEXT NOT NULL DEFAULT 'VIDEO',
    "LOCAL" TEXT,
    "LINKREUNIAO" TEXT,
    "CODUSUENTREV" BIGINT,
    "STATUS" TEXT NOT NULL DEFAULT 'AGENDADA',
    "PARECER" TEXT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,

    CONSTRAINT "TREENTREV_pkey" PRIMARY KEY ("CODENTREV")
);

-- CreateIndex
CREATE INDEX "TREENTREVHOR_CODTEN_CODVAG_DHINICIO_idx" ON "TREENTREVHOR"("CODTEN", "CODVAG", "DHINICIO");

-- CreateIndex
CREATE INDEX "TREENTREV_CODTEN_CODCDT_idx" ON "TREENTREV"("CODTEN", "CODCDT");

-- CreateIndex
CREATE INDEX "TREENTREV_CODTEN_DHINICIO_idx" ON "TREENTREV"("CODTEN", "DHINICIO");

-- AddForeignKey
ALTER TABLE "TREENTREVHOR" ADD CONSTRAINT "TREENTREVHOR_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREENTREVHOR" ADD CONSTRAINT "TREENTREVHOR_CODVAG_fkey" FOREIGN KEY ("CODVAG") REFERENCES "TREVAG"("CODVAG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREENTREV" ADD CONSTRAINT "TREENTREV_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREENTREV" ADD CONSTRAINT "TREENTREV_CODCDT_fkey" FOREIGN KEY ("CODCDT") REFERENCES "TRECDT"("CODCDT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREENTREV" ADD CONSTRAINT "TREENTREV_CODHOR_fkey" FOREIGN KEY ("CODHOR") REFERENCES "TREENTREVHOR"("CODHOR") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREENTREV" ADD CONSTRAINT "TREENTREV_CODUSUENTREV_fkey" FOREIGN KEY ("CODUSUENTREV") REFERENCES "TSIUSU"("CODUSU") ON DELETE SET NULL ON UPDATE CASCADE;


-- SelX: RLS (ADR-0002) — as duas são por tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TREENTREVHOR','TREENTREV'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
