-- DropForeignKey
ALTER TABLE "TFPDEP" DROP CONSTRAINT "TFPDEP_CODFUN_fkey";

-- DropForeignKey
ALTER TABLE "TFPDEP" DROP CONSTRAINT "TFPDEP_CODTEN_fkey";

-- DropTable
DROP TABLE "TFPDEP";

-- CreateTable
CREATE TABLE "TFPDPD" (
    "CODDPD" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODFUN" BIGINT NOT NULL,
    "NOMEDPD" TEXT NOT NULL,
    "TIPODPD" TEXT NOT NULL,
    "DTNASC" DATE,
    "CGC" TEXT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TFPDPD_pkey" PRIMARY KEY ("CODDPD")
);

-- CreateTable
CREATE TABLE "TSXSES" (
    "CODSES" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODUSU" BIGINT NOT NULL,
    "TOKENHASH" TEXT NOT NULL,
    "DHEXP" TIMESTAMP(3) NOT NULL,
    "DHREVOG" TIMESTAMP(3),
    "AGENTE" TEXT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TSXSES_pkey" PRIMARY KEY ("CODSES")
);

-- CreateIndex
CREATE INDEX "TFPDPD_CODTEN_CODFUN_idx" ON "TFPDPD"("CODTEN", "CODFUN");

-- CreateIndex
CREATE UNIQUE INDEX "TSXSES_TOKENHASH_key" ON "TSXSES"("TOKENHASH");

-- CreateIndex
CREATE INDEX "TSXSES_CODTEN_CODUSU_idx" ON "TSXSES"("CODTEN", "CODUSU");

-- AddForeignKey
ALTER TABLE "TFPDPD" ADD CONSTRAINT "TFPDPD_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TFPDPD" ADD CONSTRAINT "TFPDPD_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXSES" ADD CONSTRAINT "TSXSES_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXSES" ADD CONSTRAINT "TSXSES_CODUSU_fkey" FOREIGN KEY ("CODUSU") REFERENCES "TSIUSU"("CODUSU") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ===== SelX: RLS nas tabelas novas (ADR-0002) =====
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TFPDPD','TSXSES'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'CREATE POLICY politica_tenant ON %I ' ||
      'USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) ' ||
      'WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)',
      t
    );
  END LOOP;
END $$;
