-- DropForeignKey
ALTER TABLE "TGPMOD360" DROP CONSTRAINT "TGPMOD360_CODCAR_fkey";

-- DropIndex
DROP INDEX "TGPMOD360_CODTEN_CODCAR_key";

-- AlterTable
ALTER TABLE "TGPMOD360" DROP COLUMN "CODCAR",
ADD COLUMN     "CODDEP" BIGINT,
ADD COLUMN     "CODEMP" BIGINT;

-- CreateTable
CREATE TABLE "TGPMOD360ALVO" (
    "CODMODALVO" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODMOD" BIGINT NOT NULL,
    "CODFUN" BIGINT NOT NULL,

    CONSTRAINT "TGPMOD360ALVO_pkey" PRIMARY KEY ("CODMODALVO")
);

-- CreateIndex
CREATE INDEX "TGPMOD360ALVO_CODTEN_CODFUN_idx" ON "TGPMOD360ALVO"("CODTEN", "CODFUN");

-- CreateIndex
CREATE UNIQUE INDEX "TGPMOD360ALVO_CODMOD_CODFUN_key" ON "TGPMOD360ALVO"("CODMOD", "CODFUN");

-- CreateIndex
CREATE INDEX "TGPMOD360_CODTEN_ATIVO_idx" ON "TGPMOD360"("CODTEN", "ATIVO");

-- AddForeignKey
ALTER TABLE "TGPMOD360" ADD CONSTRAINT "TGPMOD360_CODEMP_fkey" FOREIGN KEY ("CODEMP") REFERENCES "TSIEMP"("CODEMP") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMOD360" ADD CONSTRAINT "TGPMOD360_CODDEP_fkey" FOREIGN KEY ("CODDEP") REFERENCES "TFPDEP"("CODDEP") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMOD360ALVO" ADD CONSTRAINT "TGPMOD360ALVO_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMOD360ALVO" ADD CONSTRAINT "TGPMOD360ALVO_CODMOD_fkey" FOREIGN KEY ("CODMOD") REFERENCES "TGPMOD360"("CODMOD") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMOD360ALVO" ADD CONSTRAINT "TGPMOD360ALVO_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE RESTRICT ON UPDATE CASCADE;



-- SelX: RLS (ADR-0002) — alvos do modelo 360 são dados do tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TGPMOD360ALVO'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
