-- CreateTable
CREATE TABLE "TGPFAT" (
    "CODFAT" BIGSERIAL NOT NULL,
    "SIGLA" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,
    "DESCRICAO" TEXT,
    "ORDEM" INTEGER NOT NULL DEFAULT 1,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TGPFAT_pkey" PRIMARY KEY ("CODFAT")
);

-- CreateTable
CREATE TABLE "TGPPER" (
    "CODPER" BIGSERIAL NOT NULL,
    "CODFAT" BIGINT NOT NULL,
    "TEXTO" TEXT NOT NULL,
    "TIPO" TEXT NOT NULL,
    "PESO" DECIMAL(3,2) NOT NULL DEFAULT 1.0,
    "STATUS" TEXT NOT NULL DEFAULT 'ATIVA',
    "VERSAO" INTEGER NOT NULL DEFAULT 1,
    "DIFICULDADEINTERPRETACAO" TEXT,
    "CATEGORIA" TEXT,
    "IDIOMA" TEXT NOT NULL DEFAULT 'pt-BR',
    "TAGSJSON" JSONB,
    "JUSTIFICATIVAMETODOLOGICA" TEXT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TGPPER_pkey" PRIMARY KEY ("CODPER")
);

-- CreateTable
CREATE TABLE "TGPESC" (
    "CODESC" BIGSERIAL NOT NULL,
    "TIPOESCALA" TEXT NOT NULL DEFAULT 'NORMATIVA_1_5',
    "VALOR" INTEGER NOT NULL,
    "ROTULO" TEXT NOT NULL,
    "ORDEM" INTEGER NOT NULL,

    CONSTRAINT "TGPESC_pkey" PRIMARY KEY ("CODESC")
);

-- CreateTable
CREATE TABLE "TGPMOD" (
    "CODMOD" BIGSERIAL NOT NULL,
    "NOME" TEXT NOT NULL,
    "VERSAO" INTEGER NOT NULL DEFAULT 1,
    "STATUS" TEXT NOT NULL DEFAULT 'RASCUNHO',
    "TEMPOESTIMADOMIN" INTEGER,
    "TEMPOESTIMADOMAX" INTEGER,
    "DHPUBLICACAO" TIMESTAMP(3),
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TGPMOD_pkey" PRIMARY KEY ("CODMOD")
);

-- CreateTable
CREATE TABLE "TGPMODPER" (
    "CODMODPER" BIGSERIAL NOT NULL,
    "CODMOD" BIGINT NOT NULL,
    "CODPER" BIGINT NOT NULL,
    "ORDEM" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "TGPMODPER_pkey" PRIMARY KEY ("CODMODPER")
);

-- CreateTable
CREATE TABLE "TGPPERVAG" (
    "CODPERVAG" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODVAG" BIGINT NOT NULL,
    "CODMOD" BIGINT NOT NULL,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,

    CONSTRAINT "TGPPERVAG_pkey" PRIMARY KEY ("CODPERVAG")
);

-- CreateTable
CREATE TABLE "TGPPERVAGFAT" (
    "CODPERVAGFAT" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODPERVAG" BIGINT NOT NULL,
    "CODFAT" BIGINT NOT NULL,
    "MINIMO" INTEGER NOT NULL,
    "MAXIMO" INTEGER NOT NULL,
    "PESO" DECIMAL(3,2) NOT NULL DEFAULT 1.0,
    "IMPORTANCIA" TEXT NOT NULL DEFAULT 'MEDIA',
    "ELIMINATORIO" CHAR(1) NOT NULL DEFAULT 'N',
    "JUSTIFICATIVA" TEXT,
    "TOLERANCIA" INTEGER,

    CONSTRAINT "TGPPERVAGFAT_pkey" PRIMARY KEY ("CODPERVAGFAT")
);

-- CreateTable
CREATE TABLE "TGPCONV" (
    "CODCONV" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCDT" BIGINT NOT NULL,
    "CODMOD" BIGINT NOT NULL,
    "TOKENPUB" TEXT NOT NULL,
    "STATUS" TEXT NOT NULL DEFAULT 'PENDENTE',
    "DHENVIO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHEXPIRACAO" TIMESTAMP(3),
    "CODUSUINC" BIGINT,

    CONSTRAINT "TGPCONV_pkey" PRIMARY KEY ("CODCONV")
);

-- CreateTable
CREATE TABLE "TGPSES" (
    "CODSES" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCONV" BIGINT NOT NULL,
    "DHINICIO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODULTIMAPERGUNTA" BIGINT,
    "DHCONCLUSAO" TIMESTAMP(3),
    "TEMPOTOTALSEG" INTEGER,

    CONSTRAINT "TGPSES_pkey" PRIMARY KEY ("CODSES")
);

-- CreateTable
CREATE TABLE "TGPCONSENT" (
    "CODCONSENT" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODSES" BIGINT NOT NULL,
    "DHACEITE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "IP" TEXT,

    CONSTRAINT "TGPCONSENT_pkey" PRIMARY KEY ("CODCONSENT")
);

-- CreateTable
CREATE TABLE "TGPRESP" (
    "CODRESP" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODSES" BIGINT NOT NULL,
    "CODPER" BIGINT NOT NULL,
    "CODESC" BIGINT NOT NULL,
    "DHRESPOSTA" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TGPRESP_pkey" PRIMARY KEY ("CODRESP")
);

-- CreateTable
CREATE TABLE "TGPRESULT" (
    "CODRESULT" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODSES" BIGINT NOT NULL,
    "VERSAOALGORITMO" TEXT NOT NULL,
    "VERSAOMOD" INTEGER NOT NULL,
    "INDICADORCONSISTENCIA" TEXT NOT NULL,
    "PERCRESPNEUTRAS" DECIMAL(5,2) NOT NULL,
    "PERCRESPUNIFORMES" DECIMAL(5,2) NOT NULL,
    "TEMPOTOTALSEG" INTEGER,
    "DHCALC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TGPRESULT_pkey" PRIMARY KEY ("CODRESULT")
);

-- CreateTable
CREATE TABLE "TGPRESULTFAT" (
    "CODRESULTFAT" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODRESULT" BIGINT NOT NULL,
    "CODFAT" BIGINT NOT NULL,
    "PONTUACAOBRUTA" DECIMAL(8,2) NOT NULL,
    "MINIMOPOSSIVEL" DECIMAL(8,2) NOT NULL,
    "MAXIMOPOSSIVEL" DECIMAL(8,2) NOT NULL,
    "PERCENTUALNORMALIZADO" DECIMAL(5,2) NOT NULL,
    "MEDIA" DECIMAL(5,2) NOT NULL,
    "DESVIO" DECIMAL(5,2) NOT NULL,
    "FAIXAINTERPRETATIVA" TEXT NOT NULL,

    CONSTRAINT "TGPRESULTFAT_pkey" PRIMARY KEY ("CODRESULTFAT")
);

-- CreateTable
CREATE TABLE "TGPADERVAG" (
    "CODADERVAG" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODRESULT" BIGINT NOT NULL,
    "CODPERVAG" BIGINT NOT NULL,
    "ADERENCIAGERAL" DECIMAL(5,2) NOT NULL,
    "VERSAO" TEXT NOT NULL,
    "DHCALC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TGPADERVAG_pkey" PRIMARY KEY ("CODADERVAG")
);

-- CreateTable
CREATE TABLE "TGPADERVAGFAT" (
    "CODADERVAGFAT" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODADERVAG" BIGINT NOT NULL,
    "CODFAT" BIGINT NOT NULL,
    "DISTANCIAFAIXA" DECIMAL(5,2) NOT NULL,
    "ADERENCIADIMENSAO" DECIMAL(5,2) NOT NULL,
    "DENTRODAFAIXA" CHAR(1) NOT NULL,

    CONSTRAINT "TGPADERVAGFAT_pkey" PRIMARY KEY ("CODADERVAGFAT")
);

-- CreateTable
CREATE TABLE "TGPIARESUMO" (
    "CODIARESUMO" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODRESULT" BIGINT NOT NULL,
    "TIPO" TEXT NOT NULL,
    "CONTEUDOJSON" JSONB NOT NULL,
    "MODELOUSADO" TEXT,
    "VERSAOPROMPT" TEXT,
    "DURACAOMS" INTEGER,
    "STATUS" TEXT NOT NULL DEFAULT 'OK',
    "TENTATIVAS" INTEGER NOT NULL DEFAULT 1,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TGPIARESUMO_pkey" PRIMARY KEY ("CODIARESUMO")
);

-- CreateIndex
CREATE UNIQUE INDEX "TGPFAT_SIGLA_key" ON "TGPFAT"("SIGLA");

-- CreateIndex
CREATE INDEX "TGPPER_CODFAT_idx" ON "TGPPER"("CODFAT");

-- CreateIndex
CREATE UNIQUE INDEX "TGPMODPER_CODMOD_CODPER_key" ON "TGPMODPER"("CODMOD", "CODPER");

-- CreateIndex
CREATE INDEX "TGPPERVAG_CODTEN_CODVAG_idx" ON "TGPPERVAG"("CODTEN", "CODVAG");

-- CreateIndex
CREATE UNIQUE INDEX "TGPPERVAGFAT_CODPERVAG_CODFAT_key" ON "TGPPERVAGFAT"("CODPERVAG", "CODFAT");

-- CreateIndex
CREATE UNIQUE INDEX "TGPCONV_TOKENPUB_key" ON "TGPCONV"("TOKENPUB");

-- CreateIndex
CREATE INDEX "TGPCONV_CODTEN_CODCDT_idx" ON "TGPCONV"("CODTEN", "CODCDT");

-- CreateIndex
CREATE UNIQUE INDEX "TGPSES_CODCONV_key" ON "TGPSES"("CODCONV");

-- CreateIndex
CREATE UNIQUE INDEX "TGPCONSENT_CODSES_key" ON "TGPCONSENT"("CODSES");

-- CreateIndex
CREATE INDEX "TGPRESP_CODTEN_CODSES_idx" ON "TGPRESP"("CODTEN", "CODSES");

-- CreateIndex
CREATE UNIQUE INDEX "TGPRESP_CODSES_CODPER_key" ON "TGPRESP"("CODSES", "CODPER");

-- CreateIndex
CREATE UNIQUE INDEX "TGPRESULT_CODSES_key" ON "TGPRESULT"("CODSES");

-- CreateIndex
CREATE UNIQUE INDEX "TGPRESULTFAT_CODRESULT_CODFAT_key" ON "TGPRESULTFAT"("CODRESULT", "CODFAT");

-- CreateIndex
CREATE UNIQUE INDEX "TGPADERVAG_CODRESULT_CODPERVAG_key" ON "TGPADERVAG"("CODRESULT", "CODPERVAG");

-- CreateIndex
CREATE UNIQUE INDEX "TGPADERVAGFAT_CODADERVAG_CODFAT_key" ON "TGPADERVAGFAT"("CODADERVAG", "CODFAT");

-- AddForeignKey
ALTER TABLE "TGPPER" ADD CONSTRAINT "TGPPER_CODFAT_fkey" FOREIGN KEY ("CODFAT") REFERENCES "TGPFAT"("CODFAT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMODPER" ADD CONSTRAINT "TGPMODPER_CODMOD_fkey" FOREIGN KEY ("CODMOD") REFERENCES "TGPMOD"("CODMOD") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMODPER" ADD CONSTRAINT "TGPMODPER_CODPER_fkey" FOREIGN KEY ("CODPER") REFERENCES "TGPPER"("CODPER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPPERVAG" ADD CONSTRAINT "TGPPERVAG_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPPERVAG" ADD CONSTRAINT "TGPPERVAG_CODVAG_fkey" FOREIGN KEY ("CODVAG") REFERENCES "TREVAG"("CODVAG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPPERVAG" ADD CONSTRAINT "TGPPERVAG_CODMOD_fkey" FOREIGN KEY ("CODMOD") REFERENCES "TGPMOD"("CODMOD") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPPERVAGFAT" ADD CONSTRAINT "TGPPERVAGFAT_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPPERVAGFAT" ADD CONSTRAINT "TGPPERVAGFAT_CODPERVAG_fkey" FOREIGN KEY ("CODPERVAG") REFERENCES "TGPPERVAG"("CODPERVAG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPPERVAGFAT" ADD CONSTRAINT "TGPPERVAGFAT_CODFAT_fkey" FOREIGN KEY ("CODFAT") REFERENCES "TGPFAT"("CODFAT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPCONV" ADD CONSTRAINT "TGPCONV_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPCONV" ADD CONSTRAINT "TGPCONV_CODCDT_fkey" FOREIGN KEY ("CODCDT") REFERENCES "TRECDT"("CODCDT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPCONV" ADD CONSTRAINT "TGPCONV_CODMOD_fkey" FOREIGN KEY ("CODMOD") REFERENCES "TGPMOD"("CODMOD") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPSES" ADD CONSTRAINT "TGPSES_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPSES" ADD CONSTRAINT "TGPSES_CODCONV_fkey" FOREIGN KEY ("CODCONV") REFERENCES "TGPCONV"("CODCONV") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPCONSENT" ADD CONSTRAINT "TGPCONSENT_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPCONSENT" ADD CONSTRAINT "TGPCONSENT_CODSES_fkey" FOREIGN KEY ("CODSES") REFERENCES "TGPSES"("CODSES") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPRESP" ADD CONSTRAINT "TGPRESP_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPRESP" ADD CONSTRAINT "TGPRESP_CODSES_fkey" FOREIGN KEY ("CODSES") REFERENCES "TGPSES"("CODSES") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPRESP" ADD CONSTRAINT "TGPRESP_CODPER_fkey" FOREIGN KEY ("CODPER") REFERENCES "TGPPER"("CODPER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPRESP" ADD CONSTRAINT "TGPRESP_CODESC_fkey" FOREIGN KEY ("CODESC") REFERENCES "TGPESC"("CODESC") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPRESULT" ADD CONSTRAINT "TGPRESULT_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPRESULT" ADD CONSTRAINT "TGPRESULT_CODSES_fkey" FOREIGN KEY ("CODSES") REFERENCES "TGPSES"("CODSES") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPRESULTFAT" ADD CONSTRAINT "TGPRESULTFAT_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPRESULTFAT" ADD CONSTRAINT "TGPRESULTFAT_CODRESULT_fkey" FOREIGN KEY ("CODRESULT") REFERENCES "TGPRESULT"("CODRESULT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPRESULTFAT" ADD CONSTRAINT "TGPRESULTFAT_CODFAT_fkey" FOREIGN KEY ("CODFAT") REFERENCES "TGPFAT"("CODFAT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPADERVAG" ADD CONSTRAINT "TGPADERVAG_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPADERVAG" ADD CONSTRAINT "TGPADERVAG_CODRESULT_fkey" FOREIGN KEY ("CODRESULT") REFERENCES "TGPRESULT"("CODRESULT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPADERVAG" ADD CONSTRAINT "TGPADERVAG_CODPERVAG_fkey" FOREIGN KEY ("CODPERVAG") REFERENCES "TGPPERVAG"("CODPERVAG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPADERVAGFAT" ADD CONSTRAINT "TGPADERVAGFAT_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPADERVAGFAT" ADD CONSTRAINT "TGPADERVAGFAT_CODADERVAG_fkey" FOREIGN KEY ("CODADERVAG") REFERENCES "TGPADERVAG"("CODADERVAG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPADERVAGFAT" ADD CONSTRAINT "TGPADERVAGFAT_CODFAT_fkey" FOREIGN KEY ("CODFAT") REFERENCES "TGPFAT"("CODFAT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPIARESUMO" ADD CONSTRAINT "TGPIARESUMO_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPIARESUMO" ADD CONSTRAINT "TGPIARESUMO_CODRESULT_fkey" FOREIGN KEY ("CODRESULT") REFERENCES "TGPRESULT"("CODRESULT") ON DELETE RESTRICT ON UPDATE CASCADE;


-- SelX: RLS (ADR-0002) — só tabelas por tenant; TGPFAT/TGPPER/TGPESC/TGPMOD/TGPMODPER
-- são catálogo GLOBAL (metodologia própria, sem CODTEN) — ver "01 - Modelo de Dados.md".
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TGPPERVAG','TGPPERVAGFAT','TGPCONV','TGPSES','TGPCONSENT','TGPRESP','TGPRESULT','TGPRESULTFAT','TGPADERVAG','TGPADERVAGFAT','TGPIARESUMO'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
