-- CreateTable
CREATE TABLE "TGPPERPAD" (
    "CODPERPAD" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,

    CONSTRAINT "TGPPERPAD_pkey" PRIMARY KEY ("CODPERPAD")
);

-- CreateTable
CREATE TABLE "TGPPERPADFAT" (
    "CODPERPADFAT" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODPERPAD" BIGINT NOT NULL,
    "CODFAT" BIGINT NOT NULL,
    "MINIMO" INTEGER NOT NULL,
    "MAXIMO" INTEGER NOT NULL,
    "PESO" DECIMAL(3,2) NOT NULL DEFAULT 1.0,
    "IMPORTANCIA" TEXT NOT NULL DEFAULT 'MEDIA',
    "ELIMINATORIO" CHAR(1) NOT NULL DEFAULT 'N',
    "JUSTIFICATIVA" TEXT,
    "TOLERANCIA" INTEGER,

    CONSTRAINT "TGPPERPADFAT_pkey" PRIMARY KEY ("CODPERPADFAT")
);

-- CreateIndex
CREATE INDEX "TGPPERPAD_CODTEN_idx" ON "TGPPERPAD"("CODTEN");

-- CreateIndex
CREATE UNIQUE INDEX "TGPPERPADFAT_CODPERPAD_CODFAT_key" ON "TGPPERPADFAT"("CODPERPAD", "CODFAT");

-- AddForeignKey
ALTER TABLE "TGPPERPAD" ADD CONSTRAINT "TGPPERPAD_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPPERPADFAT" ADD CONSTRAINT "TGPPERPADFAT_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPPERPADFAT" ADD CONSTRAINT "TGPPERPADFAT_CODPERPAD_fkey" FOREIGN KEY ("CODPERPAD") REFERENCES "TGPPERPAD"("CODPERPAD") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPPERPADFAT" ADD CONSTRAINT "TGPPERPADFAT_CODFAT_fkey" FOREIGN KEY ("CODFAT") REFERENCES "TGPFAT"("CODFAT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- SelX: RLS (ADR-0002) — TGPPERPAD/TGPPERPADFAT são por tenant (o padrão em si é
-- configuração do tenant, mesmo que aponte pro catálogo global TGPFAT).
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TGPPERPAD','TGPPERPADFAT'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;

