-- AlterTable
ALTER TABLE "TFPFUN" ADD COLUMN     "CODCONTRATO" BIGINT,
ADD COLUMN     "CODPROJ" BIGINT;

-- CreateTable
CREATE TABLE "TCSPRJ" (
    "CODPROJ" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "DESCRPROJ" TEXT NOT NULL,
    "CODEMP" BIGINT,
    "CODPROJERP" BIGINT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TCSPRJ_pkey" PRIMARY KEY ("CODPROJ")
);

-- CreateTable
CREATE TABLE "TCSCON" (
    "CODCONTRATO" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "NUMCONTRATO" TEXT,
    "DESCRCONTRATO" TEXT NOT NULL,
    "CODEMP" BIGINT,
    "CODCONTRATOERP" BIGINT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TCSCON_pkey" PRIMARY KEY ("CODCONTRATO")
);

-- CreateIndex
CREATE INDEX "TCSPRJ_CODTEN_idx" ON "TCSPRJ"("CODTEN");

-- CreateIndex
CREATE INDEX "TCSCON_CODTEN_idx" ON "TCSCON"("CODTEN");

-- AddForeignKey
ALTER TABLE "TFPFUN" ADD CONSTRAINT "TFPFUN_CODPROJ_fkey" FOREIGN KEY ("CODPROJ") REFERENCES "TCSPRJ"("CODPROJ") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TFPFUN" ADD CONSTRAINT "TFPFUN_CODCONTRATO_fkey" FOREIGN KEY ("CODCONTRATO") REFERENCES "TCSCON"("CODCONTRATO") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TCSPRJ" ADD CONSTRAINT "TCSPRJ_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TCSCON" ADD CONSTRAINT "TCSCON_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;


-- SelX: RLS (ADR-0002)
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TCSPRJ','TCSCON'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
