-- CreateTable
CREATE TABLE "TGPALERTA" (
    "CODALERTA" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODFUN" BIGINT NOT NULL,
    "CHAVE" TEXT NOT NULL,
    "STATUS" TEXT NOT NULL DEFAULT 'ABERTO',
    "MOTIVO" TEXT,
    "CODUSURESP" BIGINT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHALT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TGPALERTA_pkey" PRIMARY KEY ("CODALERTA")
);

-- CreateIndex
CREATE INDEX "TGPALERTA_CODTEN_CODFUN_idx" ON "TGPALERTA"("CODTEN", "CODFUN");

-- CreateIndex
CREATE UNIQUE INDEX "TGPALERTA_CODTEN_CODFUN_CHAVE_key" ON "TGPALERTA"("CODTEN", "CODFUN", "CHAVE");

-- AddForeignKey
ALTER TABLE "TGPALERTA" ADD CONSTRAINT "TGPALERTA_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPALERTA" ADD CONSTRAINT "TGPALERTA_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPALERTA" ADD CONSTRAINT "TGPALERTA_CODUSURESP_fkey" FOREIGN KEY ("CODUSURESP") REFERENCES "TSIUSU"("CODUSU") ON DELETE SET NULL ON UPDATE CASCADE;



-- SelX: RLS (ADR-0002) — estado de alerta é dado do funcionário, por tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TGPALERTA'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
