-- AlterTable
ALTER TABLE "TSXTEN" DROP COLUMN "PROVEDORIA";

-- CreateTable
CREATE TABLE "TSXIACFG" (
    "CODIACFG" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "PROVEDORIA" TEXT NOT NULL DEFAULT 'nuvem',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,

    CONSTRAINT "TSXIACFG_pkey" PRIMARY KEY ("CODIACFG")
);

-- CreateIndex
CREATE UNIQUE INDEX "TSXIACFG_CODTEN_key" ON "TSXIACFG"("CODTEN");

-- AddForeignKey
ALTER TABLE "TSXIACFG" ADD CONSTRAINT "TSXIACFG_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;


-- SelX: RLS (ADR-0002) — TSXIACFG é configuração por tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TSXIACFG'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
